# -*- coding: utf-8 -*-
"""09.02.2024.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pWLK3-RRHz5mpDOM9Zgn13c7uP--oMky

```
PROGRAMA LOOP

VAR

  X, R, CONT = int

INICIO

  PARA CONT DE 1 ATÉ 4 PASSO ++ FAÇA

    ESCREVA("INSIRA UM VALOR")
    LEIA (X)

    R <- X * 12
    ESCREVA("O resultado é: ", R)
  FIM_PARA

FIM
```
"""

for cont in range(4):
  X = float(input("Digite um valor para X: "))
  R = X * 12
  print("O resultado é:", R)