# -*- coding: utf-8 -*-
"""15.02.2024.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s7U5fcVvk1v5KbuqTrqqoTEZw86P_hIu

#1 Faça um programa que leia 5 numeros e informe o maior número
"""

maior_numero = float('-inf')

for banana in range(5):
  numero = float(input(f"Digite o {banana + 1} numero: "))
  if numero > maior_numero:
    maior_numero = numero

  print(f"O maior numero digitado é: {maior_numero}")

"""#2 Faça um programa que verifique e mostre os números entre 1.000 e 2.000 (inclusive) que, quando divididos por 11 produzam resto igual a 2."""

for numero in range(1000, 2001):
  if numero % 11 == 2:
    print(numero)

"""#3 Faça um programa que leia 5 números e informe a soma e a média dos números"""

soma = 0
for cont in range(5):
  numero = float(input("Digite a nota:"))
  soma += numero
print(f"A média é {soma /5}")

"""#4 Faça um programa que receba um número e usando laços de repetição calcule e mostre a tabuada desse número"""

numero = int(input("Digite um numero que você não sabe a tabuada"))
print(f"Tabuada de {numero}")
for contador in range(1, 11):
  resultado = numero *contador
  print(f"{numero} x {contador} = {resultado}")

"""#5 Faça um programa que mostre as tabuadas dos números de 1 a 10 usando laços de repetição"""

for numero in range (1,11):
  print("")
  print(f"Tabuada de {numero}")
  for contador in range(1, 11):
    resultado = numero *contador
    print(f"{numero} x {contador} = {resultado}")

"""#6 Faça um programa que imprima na tela os números de 1 a 20, um abaixo do outro. Depois modifique o programa para que ele mostre os numeros um ao lado do outro"""

for i in range(1, 21):
  print(i)
print(list(range(1, 21)))

"""#7 Faça um programa que imprima na tela apenas os números ímpares entre 1 e 50"""

print("Números ímpares de 1 a 50.")
for numero in range(1, 51):
  if numero % 2 != 0:
    print(numero)

"""#8 Faça um programa que receba dois números inteiros e gere os números inteiros que estão no intervalo compreendido por eles"""

numero1 = int(input("Informe o número 1:"))
numero2 = int(input("Informe o número 2:"))

if numero1 < numero2:
  for cont in range((numero1 + 1), numero2):
    print(cont)
else:
  for cont in range((numero2 + 1), numero1):
    print(cont)

"""#9 Uma loja deseja cadastrar 5 clientes e verificar se o faturamento da loja foi superior a loja b (faturamento = 54000). Se o faturamento atingir esse valor mostre na tela uma mensagem contendo em quanto foi superado o faturamento."""

faturamento_a = 0
faturamento_b = 54000
for cliente in range(1, 6):
  valor = int(input(f"Insira o valor do cliente {cliente}: "))
  faturamento_a += valor

if faturamento_a > faturamento_b:
  print(f"A loja A superou o faturamento da loja B em R${faturamento_a - faturamento_b}")
else:
  print(f"A loja B superou o faturamento da loja A em R${faturamento_b - faturamento_a}")

"""#10 Faça um programa que peça 10 numeros inteiros, calcule e mostre a quantidade de numeros pares e a quantidade de numeros impares"""

par = 0
impar = 04
for i in range(1,11):
  numero =int(input(f"Insira o numero inteiro [{i} de 10]:"))
  if numero % 2 == 0:
    par += 1
  else:
    impar += 1
print(f"A quantidade de números pares foi: {par}.")
print(f"A quantidade de números ímpares foi: {impar}.")

"""#11 Um funcionario foi contratado em 1995, com salario inicial de 1000;
Em 1996 recebeu aumento de 1,5% sobre seu salario inicial;
A partir de 1967 (inclusive), os aumentos salariais sempre correspondem ao dobro do percentual do ano anterior. Faça um programa que determine o salario atual desse funcionario. Apos concluir isto, altere o programa permitindo que o usuario digite o salario inicial do funcionario.
"""

salario = float(input("Informe seu salário: "))
#salario = 1000
percentual = 0.015
for i in range(1996, 2025):
  aumento = salario * percentual
  salario += aumento
  print(f"Salario ano de {i}: {salario:.3f}")
  print(f"Com percentual de: {percentual:.3f}")
  percentual *= 2

"""#12 Faça um programa que peça uma nota entre zero e dez. Mostre uma mensagem caso o valor seja inválido e continue pedindo ate que o usuario informe um valor valido."""

for i in range(1,999):
  nota = float(input("Informe uma nota: "))
  if nota >= 0 and nota <= 10:
    break;
  else:
    print("Valor inválido.")

"""#13 Uma loja tem uma política de descontos de acordo com o valor da compra do cliente. Os descontos começam acima dos R$ 500. A cada 100 reais acima dos R$ 500 o cliente ganha 1% de desconto cumulativo até 25%."""

desconto = 0
valor = float(input("Insira o valor da compra: "))

if valor >= 500:
  desconto +=1
  v1 = valor - 500
  for i in range(24):
    if v1 >= 100:
      desconto += 1
      v1 -= 100
    else:
      break;
porcentagem = (valor * desconto) / 100
valor -= porcentagem

print(valor)

"""#14 Faça um programa que receba a idade de 15 pessoas e que calcule e mostre: A) a quantidade de pessoas em cada faixa etaria B) a percentagem de pessoas na primeira e ultima faixa etaria, com relação ao total de pessoas 15, 16 a 30, 31 a 45, 46 a 60, 61"""

i15 = 0
i1630 = 0
i3145 = 0
i4660 = 0
i61 = 0
for i in range (1, 16):
  idade = int(input(f"Informe a idade da pessoa {i}: "))
  if idade <= 15:
    i15 += 1
  elif idade >= 16 and idade <= 30:
    i1630 += 1
  elif idade >= 31 and idade <= 45:
    i3145 += 1
  elif idade >= 46 and idade <= 60:
    i4660 += 1
  elif idade >= 61 :
    i61 += 1

print("QUANTIDADE POR FAIXA DE IDADE:")
print(f"Idade até 15: {i15}")
print(f"Idade entre 16 e 30: {i1630}")
print(f"Idade entre 31 e 45: {i3145}")
print(f"Idade entre 46 e 60: {i4660}")
print(f"Idade acima de 60: {i61}")

print("PORCENTAGEM POR FAIXA DE IDADE:")
print(f"Idade até 15: {(i15 * 100) / 15:.2f}")
print(f"Idade entre 16 e 30: {(i1630 * 100) / 15:.2f}")
print(f"Idade entre 31 e 45: {(i3145 * 100) / 15:.2f}")
print(f"Idade entre 46 e 60: {(i4660 * 100) / 15:.2f}")
print(f"Idade acima de 60: {(i61 * 100) / 15:.2f}")

"""#15 Faça um programa que peça dois numeros, base e expoente, calcule e mostre o primeiro numero elevado ao segundo numero. Não utilize a função de potencia da linguagem"""

n1 = int(input("Informe o numero base: "))
n2 = int(input("Informe o numero expoente: "))
resultado = n1
for i in range(n2 -1):
  resultado *= n1
print(f"O resultado foi {resultado}.")

"""#16 Faça um programa que mostre todos os primos entre 1 e N sendo N um numero inteiro fornecido pelo usuario. O programa devera mostrar tambem o numero de divisoes que ele executou para encontrar os numeros primos. Serão avaliados o funcionamento, o estilo e o numero de testes (divisoes) executados."""

teste = 0
N = int(input("Informe um numero inteiro: "))
for i in range(2, N +1):
  teste += 1

    print(i)